server.port: 9095
spring:
  main.banner-mode: off
  profiles.active: local

spring.cloud:
  stream:
    bindings:
      book-input.destination: books
      author-output.destination: books
      publisher-output.destination: books
    kafka.streams:
      binder:
        deserializationExceptionHandler: logAndContinue
        brokers: localhost:9092
        configuration.schema.registry.url: http://localhost:8081
      bindings:
        book-input.consumer.valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        author-output.producer.valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        publisher-output.producer.valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                
