server.port: 9091
spring:
  main.banner-mode: off
  profiles.active: aws

logging.level.root: info

app:
  aws.region: ${AWS_REGION}
  kafka:
    schema-registry-name: ${SCHEMA_REGISTRY_NAME}
    schema-registry-url: ${SCHEMA_REGISTRY_URL}
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    producer:
      serialization:
        value-class: ${SERIALIZER_VALUE_CLASS}
        key-class: ${SERIALIZER_KEY_CLASS}
