server.port: 9095
spring:
  main.banner-mode: off

app:
  aws.region: ${AWS_REGION}
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    schema-registry-name: ${SCHEMA_REGISTRY_NAME}
    producer:
      topics.dead-letter: dead-letter
      serialization:
        value-class: ${SERIALIZER_VALUE_CLASS}
        key-class: ${SERIALIZER_KEY_CLASS}
    streams:
      topics:
        input.books: books
        output.magazines: magazines
      auto-offset: earliest
      serde:
        key-class: ${SERDE_KEY_CLASS}
        value-class: ${SERDE_VALUE_CLASS}

logging:
  level.root: INFO
  json:
    prettify: true
    timestamp-format: yyyy-MM-dd' 'HH:mm:ss.SSS

cloud.aws:
  region:
    static: ${AWS_REGION}
    auto: false
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_ACCESS_KEY_SECRET}
