server.port: 9096
spring:
  main.banner-mode: off
  profiles.active: local

app:
  kafka:
    required-headers: authentication,correlation-id,source
    streams:
      topics:
        input.magazines: magazines
      bootstrap-servers: localhost:9092
      schema-registry-url: http://localhost:8081
      auto-offset: earliest
      serde:
        key-class: org.apache.kafka.common.serialization.Serdes$StringSerde
        value-class: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde

logging:
  level.root: INFO
  json:
    prettify: false
    timestamp-format: yyyy-MM-dd' 'HH:mm:ss.SSS
