server.port: 9096
spring:
  main.banner-mode: off

app:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    schema-registry-name: ${SCHEMA_REGISTRY_NAME}
    streams:
      topics:
        input.magazines: magazines
      auto-offset: earliest
      serde:
        key-class: ${SERDE_KEY_CLASS}
        value-class: ${SERDE_VALUE_CLASS}

logging:
  level.root: INFO
  json:
    prettify: false
    timestamp-format: yyyy-MM-dd' 'HH:mm:ss.SSS

cloud.aws:
  region:
    static: ${AWS_REGION}
    auto: false
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_ACCESS_KEY_SECRET}
